# config-management.yaml
apiVersion: configmanagement.gke.io/v1
kind: ConfigManagement
metadata:
  name: config-management
spec:

#Config Sync 
  clusterName: gcp-gke
  git:
    syncRepo: git@github.com:virenr90/acm.git
    syncBranch: main
    secretType: ssh
    policyDir: "config"
  sourceFormat: unstructured
  #sourceFormat: hierarchy

  # Set to true to install and enable Config Connector
  configConnector:
    enabled: true

  # ...other fields...

# Set to true to enable hierarchical namespaces
  hierarchyController:
    enabled: true
    # Comment to disable hierarhical quota:
    enableHierarchicalResourceQuota: true
    # Comment to disable hierarchical observability:
    enablePodTreeLabels: true
   # ...other fields...

  
# Set to true to install and enable Policy Controller
  policyController:
    enabled: true
    # Uncomment to prevent the template library from being installed
    # templateLibraryInstalled: false
    # Uncomment to enable support for referential constraints
    referentialRulesEnabled: true
    # Uncomment to disable audit, adjust value to set audit interval
    # auditIntervalSeconds: 0
    # Uncomment to log all denies and dryrun failures
    # logDeniesEnabled: true
    # Uncomment to exempt namespaces
    exemptableNamespaces: ["gm2"]
  # ...other fields...