apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: eng
  labels:
    app: busybox
spec:
  containers:
  - image: busybox
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: busyybox
  restartPolicy: Always