  apiVersion: pubsub.cnrm.cloud.google.com/v1beta1
  kind: PubSubTopic
  metadata:
    annotations:
    cnrm.cloud.google.com/organization-id: "808008667013"
    labels:
      environment: dev
    name: org-ns-anots
    project: "642743042865"
    namespace: ns-org
   
