  apiVersion: pubsub.cnrm.cloud.google.com/v1beta1
  kind: PubSubTopic
  metadata:
    labels:
      environment: dev
    name: org-ns-anots
    organization-id: "808008667013"
    project-id: anthos-313604
    namespace: ns-org